export interface ProductOffer {
  asin: string[];
  brand: string;
  brand_id: number;
  category: string;
  category_id: number;
  datasheet_available: boolean;
  description: string;
  ean: string;
  energy_efficiency_class: string | null;
  energy_efficiency_cool: string | null;
  energy_efficiency_heat: string | null;
  energy_efficiency_scale: string | null;
  gtin: string[];
  has_image: boolean;
  image_url_large: string;
  image_url_small: string;
  images: any[];
  indexable: boolean;
  is_deleted: boolean;
  legal_fields: {
    eu_labels: any;
    non_eu_labels: any;
  };
  max_price: string;
  min_price: string;
  mpnr: string[];
  name: string;
  offer_count: number;
  offers: any[];
  payment_methods: number[];
  price_offer_count: null | number;
  product_id: number;
  product_url: string;
  product_variant_ids: string[];
  properties: any;
  pzn: string[];
  relevance: number;
  score: number;
  test_count: number;
  test_rating: number | null;
  type: string;
  userreview_count: number;
  userreview_rating: number;
}

export interface Offer {
  article_id: string | null;
  asin: string[];
  availability_code: string;
  availability_text: string;
  brand: string;
  brand_id: number;
  category: string;
  category_id: number;
  clickout_link: string;
  cpc: number;
  delivery_asia: string | null;
  description: string;
  energy_efficiency_class: string | null;
  energy_efficiency_cool: string | null;
  energy_efficiency_heat: string | null;
  export_price: string | null;
  gtin: string[];
  has_image: boolean;
  image_url: string;
  image_url_large: string;
  legal_fields: {
    eu_labels: any;
    non_eu_labels: any;
  };
  mobile_optimized: boolean;
  mpnr: string[];
  name: string;
  offer_id: number;
  old_price: string | null;
  payment_methods: number[];
  price: string;
  price_per_unit: string;
  product_id: number;
  promo_text: string | null;
  pzn: string[];
  relevance: number;
  score: number;
  shipping_costs: string;
  shipping_costs_at: string | null;
  shop: string;
  shop_id: number;
  shop_logo_url: string;
  shop_userreview_count: number;
  shop_userreview_rating: number;
  sku: string | null;
  stock_quantity: string | null;
  tires_fuel_efficiency: string | null;
  tires_rolling_noise: string | null;
  tires_wet_grip: string | null;
  total_price: string;
  total_price_at: string | null;
  type: string;
  voucher_text: string | null;
}
